name: gh-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: MkDocs Github Pages automatic deployment
    runs-on: windows-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: MkDocs gh-deploy
        run: |
          git pull
          mkdocs gh-deploy

site_name: Ahmed Omar's Software Projects
site_url: https://ahmedomarsoftware.com
theme:
  name: mkdocs
  color_mode: dark
  user_color_mode_toggle: true
  Default: true
